name: readthedocs
dependencies:
- python=3.5
- curl
- cython
- h5py
- hdf5
- ipykernel
- ipython
- ipython_genutils
- jupyter_client
- jupyter_core
- libnetcdf
- matplotlib
- nbconvert
- nbformat
- netcdf4
- notebook
- numpy
- pandas
- scikit-learn
- scipy
- seaborn
